
const STORAGE_KEY='travelPokedexTrips';
const SCHEMA_VERSION=2;
const defaults=[
{id:'vegas',title:'Las Vegas',start:'2026-08-04',end:'2026-08-10',story:'DEF CON med teamet. Teknologi, netværk og lidt for meget Vegas.',image:'assets/vegas2.svg',photos:['assets/vegas2.svg','assets/vegas.svg'],tags:['DEF CON','AREA15','Hoover Dam'],locations:[{city:'Las Vegas',country:'USA'},{city:'AREA15',country:'USA'},{city:'Hoover Dam',country:'USA'}]},
{id:'lisbon',title:'Lisbon',start:'2026-11-08',end:'2026-11-13',story:'By, mad og en tur med Sporting i kalenderen.',image:'assets/lisbon.svg',photos:['assets/lisbon.svg'],tags:['CITY','FOOD'],locations:[{city:'Lisbon',country:'Portugal'}]},
{id:'london',title:'London',start:'2026-11-14',end:'2026-11-16',story:'Weekend i London.',image:'assets/london.svg',photos:['assets/london.svg'],tags:['CITY'],locations:[{city:'London',country:'United Kingdom'}]},
{id:'germany',title:'Lübeck & Sierksdorf',start:'2025-07-01',end:'2025-07-08',story:'Family holiday.',image:'assets/germany.svg',photos:['assets/germany.svg'],tags:['FAMILY'],locations:[{city:'Lübeck',country:'Germany'},{city:'Sierksdorf',country:'Germany'}]},
{id:'italy',title:'Rome · Florence · Venice',start:'2024-06-01',end:'2024-06-10',story:'Historical memory.',image:'assets/italy.svg',photos:['assets/italy.svg'],tags:['MEMORY'],locations:[{city:'Rome',country:'Italy'},{city:'Florence',country:'Italy'},{city:'Venice',country:'Italy'}]}
];
function normalizeTrip(t){
  let locations=Array.isArray(t.locations)?t.locations.filter(x=>x&&x.city).map(x=>({city:String(x.city).trim(),country:String(x.country||t.country||'Unknown').trim()})):[];
  if(!locations.length){const cities=Array.isArray(t.cities)?t.cities:(t.cities||'').split(',').map(x=>x.trim()).filter(Boolean);locations=cities.map(city=>({city,country:String(t.country||'Unknown').trim()}));}
  return {...t,locations,photos:Array.isArray(t.photos)?t.photos:[],tags:Array.isArray(t.tags)?t.tags:[],schemaVersion:SCHEMA_VERSION};
}
function loadTrips(){
  try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return defaults.map(normalizeTrip);const parsed=JSON.parse(raw);return (parsed.trips||parsed).map(normalizeTrip)}catch(e){return defaults.map(normalizeTrip)}
}
let trips=loadTrips(),editingId=null,pendingPhotos=[],removedPhotos=[];
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({schemaVersion:SCHEMA_VERSION,trips}));renderAll();return true}catch(e){toast('Lageret er fuldt — prøv færre/store billeder');return false}}
function allLocations(){return trips.flatMap(t=>t.locations||[])}
function cityList(t){return [...new Set((t.locations||[]).map(x=>x.city).filter(Boolean))]}
function countryList(){return [...new Set(allLocations().map(x=>x.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function allCities(){return [...new Set(allLocations().map(x=>x.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function countryStats(country){const ts=trips.filter(t=>(t.locations||[]).some(l=>l.country===country));return {trips:ts.length,cities:new Set(ts.flatMap(cityList)).size,photos:ts.reduce((n,t)=>n+(t.photos||[]).length,0)} }
function tripCitiesByCountry(t){return (t.locations||[]).map(x=>`${x.city} — ${x.country}`).join(', ')}
function toast(msg){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)}
function fmt(t){if(!t)return 'Dato ikke angivet';const d=new Date(t+'T12:00:00');return d.toLocaleDateString('da-DK',{day:'numeric',month:'short',year:'numeric'}).replace('.','')}
function year(t){return t?new Date(t+'T12:00:00').getFullYear():'Ukendt'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(t){return `<div class="journeyCard" onclick="openTrip('${t.id}')"><img class="thumb" src="${t.image||'assets/vegas.svg'}"><div class="grow"><span class="small">${esc((t.locations?.[0]?.country||'').toUpperCase())} · ${fmt(t.start)}</span><h3>${esc(t.title)}</h3><span class="small">${esc(cityList(t).join(', '))}</span><div class="tags">${(t.tags||[]).slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="cardActions" onclick="event.stopPropagation()"><button class="miniBtn" onclick="openEditor('${t.id}')">Edit</button><button class="miniBtn danger" onclick="deleteTrip('${t.id}')">Delete</button></div></div><b>›</b></div>`}
function showView(id,btn){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');else{const b=document.querySelector('.nav button[data-view="'+id+'"]');if(b)b.classList.add('active')}window.scrollTo(0,0)}
function openTrip(id='vegas'){const t=trips.find(x=>x.id===id);if(!t)return;document.getElementById('trip').innerHTML=`<div class="detailHero" style="background-image:url('${t.image||'assets/vegas2.svg'}')"><button onclick="showView('trips')" style="color:white;font-size:26px">‹</button><button onclick="openEditor('${t.id}')" style="color:white;font-size:15px;background:#0006;border-radius:99px;padding:7px 10px">Edit</button><div class="title"><div style="font-size:12px;letter-spacing:.1em">${esc(t.country).toUpperCase()} · ${year(t.start)}</div><h1>${esc(t.title)}</h1><p>${fmt(t.start)}${t.end?' – '+fmt(t.end):''}</p></div></div><div class="detailBody"><div class="quote">“${esc(t.story||'Ingen historie endnu.')}”</div><div class="detailMetrics"><div class="dmetric"><b>${days(t)}</b><span>Days</span></div><div class="dmetric"><b>${cityList(t).length}</b><span>Places</span></div><div class="dmetric"><b>${(t.photos||[]).length}</b><span>Photos</span></div><div class="dmetric"><b>0</b><span>Videos</span></div></div><div class="tabs"><button class="tab active" onclick="tripTab('story',this)">Story</button><button class="tab" onclick="tripTab('moments',this)">Moments</button><button class="tab" onclick="tripTab('route',this)">Map</button><button class="tab" onclick="tripTab('media',this)">Media</button></div><div id="story"><div class="section" style="padding:8px 0"><div class="sectionTitle"><h2>Places</h2><span class="small">${cityList(t).length} cities / places</span></div><div class="tags" style="margin-bottom:16px">${cityList(t).map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div><div class="sectionTitle"><h2>Highlights</h2><span class="small">${(t.photos||[]).length} photos</span></div><div class="mediaGrid">${(t.photos||[]).map(p=>`<img src="${p}">`).join('')}</div></div></div><div id="moments" style="display:none"><div class="empty">Moments bliver næste lag i historikken.</div></div><div id="route" style="display:none"><div class="mapbox" style="margin:8px 0"><div class="mapLabel" style="left:10%;top:65%">${esc(t.title)}</div><div class="mapLabel" style="right:8%;top:25%">${esc(t.country)}</div></div></div><div id="media" style="display:none"><div class="mediaGrid" style="padding:8px 0">${(t.photos||[]).map(p=>`<img src="${p}">`).join('')}</div></div></div>`;showView('trip')}
function days(t){if(!t.start||!t.end)return '—';return Math.max(1,Math.round((new Date(t.end)-new Date(t.start))/86400000)+1)}
function tripTab(id,btn){['story','moments','route','media'].forEach(x=>document.getElementById(x).style.display=x===id?'block':'none');document.querySelectorAll('.tabs .tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function renderHome(){const recent=[...trips].sort((a,b)=>(b.start||'').localeCompare(a.start||''));document.getElementById('home').innerHTML=`<div class="top"><div class="brand">TRAVEL POKÉDEX</div></div><div class="hero"><div class="heroImage"><div class="heroText"><small>YOUR JOURNEY</small><h1>Mikkel</h1><p>Places shape people.</p></div></div></div><div class="metrics"><div class="metric"><b>${countryList().length}</b><span>Countries</span></div><div class="metric"><b>${allCities().length}</b><span>Cities</span></div><div class="metric"><b>${trips.length}</b><span>Trips</span></div><div class="metric"><b>${trips.reduce((n,t)=>n+(t.photos||[]).length,0)}</b><span>Photos</span></div></div><div class="section"><div class="sectionTitle"><h2>Recent journeys</h2><button class="small" onclick="showView('trips')">See all</button></div>${recent.slice(0,3).map(card).join('')||'<div class="empty">No journeys yet.</div>'}</div>`}
function renderTrips(){const sorted=[...trips].sort((a,b)=>(b.start||'').localeCompare(a.start||''));let html='<div class="top"><div><div class="small">YOUR HISTORY</div><h1 class="serif" style="margin:3px 0;font-size:30px">Journeys</h1></div></div><div class="timeline">';let last=null;sorted.forEach(t=>{const y=year(t.start);if(y!==last){html+=`<div class="year">${y}</div>`;last=y}html+=`<div class="timelineItem"><div class="timelineDate">${t.start?new Date(t.start+'T12:00:00').toLocaleDateString('da-DK',{month:'short'}).toUpperCase():''}</div><div class="timelineDot"></div><div>${card(t)}</div></div>`});html+='</div>';document.getElementById('trips').innerHTML=html}
function renderCollection(){const grouped=countryList();const icons=['🌍','🏛️','🏰','🌊','🏙️','🗺️'];document.getElementById('collection').innerHTML=`<div class="top"><div><div class="small">YOUR WORLD</div><h1 class="serif" style="margin:3px 0;font-size:30px">Collection</h1></div></div><input class="search" placeholder="Search countries or cities…" oninput="filterCollection(this.value)"><div id="collectionGrid" class="collectionGrid">${grouped.map((c,i)=>{const st=countryStats(c);return `<div class="country" data-search="${esc(c+' '+trips.filter(t=>(t.locations||[]).some(l=>l.country===c)).flatMap(cityList).join(' ')).toLowerCase()}"><div class="small">${icons[i%icons.length]} ${esc(c).toUpperCase()}</div><h3>${st.trips} ${st.trips===1?'visit':'visits'}</h3><p>${st.cities} cities · ${st.photos} photos</p><div class="tags">${[...new Set(trips.filter(t=>(t.locations||[]).some(l=>l.country===c)).flatMap(cityList))].slice(0,4).map(city=>`<span class="tag">${esc(city)}</span>`).join('')}</div><div class="art">${icons[i%icons.length]}</div></div>`}).join('')}</div><div class="section"><div class="sectionTitle"><h2>All cities</h2><span class="small">${allCities().length}</span></div><div class="tags">${allCities().map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div></div>`}
function filterCollection(q){document.querySelectorAll('.country').forEach(e=>e.style.display=e.dataset.search.includes(q.toLowerCase())?'block':'none')}
function renderMore(){document.getElementById('more').innerHTML=`<div class="top"><div><div class="small">YOUR JOURNEY</div><h1 class="serif" style="margin:3px 0;font-size:30px">Overview</h1></div></div><div class="section"><div class="sectionTitle"><h2>Your archive</h2><span class="small">Stored locally</span></div><div class="metrics" style="margin:0"><div class="metric"><b>${trips.length}</b><span>Trips</span></div><div class="metric"><b>${countryList().length}</b><span>Countries</span></div><div class="metric"><b>${allCities().length}</b><span>Cities</span></div><div class="metric"><b>${trips.reduce((n,t)=>n+(t.photos||[]).length,0)}</b><span>Photos</span></div></div></div><div class="section"><div class="journeyCard"><div style="font-size:28px">💾</div><div class="grow"><b>Local archive</b><div class="small">Journeys, locations and compressed photos are saved in this browser.</div><div class="dataTools" style="margin-top:12px"><button class="secondary" onclick="exportData()">Export backup</button><label class="secondary" style="text-align:center;cursor:pointer">Import backup<input type="file" accept="application/json" onchange="importData(this)" style="display:none"></label></div></div></div></div>`}
function renderExplore(){document.getElementById('explore').innerHTML=`<div class="top"><div><div class="small">YOUR WORLD</div><h1 class="serif" style="margin:3px 0;font-size:30px">Explore</h1></div></div><div class="mapbox"><div class="mapLabel" style="left:12%;top:58%">Europe</div><div class="mapLabel" style="left:62%;top:32%">USA</div><div class="mapLabel" style="right:8%;top:55%">Asia</div></div><div class="section"><div class="sectionTitle"><h2>Places visited</h2><span class="small">${countryList().length} countries · ${allCities().length} cities</span></div>${countryList().map(c=>`<span class="tag" style="display:inline-block;margin:0 5px 5px 0">${esc(c)}</span>`).join('')}</div>`}
function openEditor(id=null){
  editingId=id;pendingPhotos=[];removedPhotos=[];document.getElementById('modal').classList.add('show');
  document.getElementById('modalTitle').textContent=id?'Edit journey':'Add a journey';document.getElementById('deleteWrap').style.display=id?'flex':'none';
  const t=id?trips.find(x=>x.id===id):{};document.getElementById('fTitle').value=t.title||'';document.getElementById('fStart').value=t.start||'';document.getElementById('fEnd').value=t.end||'';document.getElementById('fStory').value=t.story||'';
  renderLocationFields(t.locations||[{city:'',country:''}]);renderPhotoPreview(t.photos||[]);document.getElementById('fPhotos').value='';
}
function closeEditor(){document.getElementById('modal').classList.remove('show')}
function renderLocationFields(locations){const wrap=document.getElementById('locationList');wrap.innerHTML=locations.length?locations.map((l,i)=>`<div class=\"locationRow\"><input data-city placeholder=\"City / place\" value=\"${esc(l.city||'')}\"><input data-country placeholder=\"Country\" value=\"${esc(l.country||'')}\"><button type=\"button\" class=\"miniBtn danger\" onclick=\"removeLocation(${i})\">×</button></div>`).join(''):'';}
function addLocation(){const rows=[...document.querySelectorAll('#locationList .locationRow')].map(r=>({city:r.querySelector('[data-city]').value,country:r.querySelector('[data-country]').value}));rows.push({city:'',country:''});renderLocationFields(rows);}
function removeLocation(i){const rows=[...document.querySelectorAll('#locationList .locationRow')].map(r=>({city:r.querySelector('[data-city]').value,country:r.querySelector('[data-country]').value}));rows.splice(i,1);renderLocationFields(rows)}
function currentLocations(){return [...document.querySelectorAll('#locationList .locationRow')].map(r=>({city:r.querySelector('[data-city]').value.trim(),country:r.querySelector('[data-country]').value.trim()})).filter(x=>x.city&&x.country)}
function renderPhotoPreview(existing){const html=existing.map((p,i)=>removedPhotos.includes(i)?'':`<div class="photoItem"><img src="${p}"><button class="photoRemove" type="button" onclick="removeExistingPhoto(${i})">×</button></div>`).join('')+pendingPhotos.map((p,i)=>`<div class="photoItem"><img src="${p}"><button class="photoRemove" type="button" onclick="removePendingPhoto(${i})">×</button></div>`).join('');document.getElementById('uploadPreview').innerHTML=html;}
function removeExistingPhoto(index){if(!removedPhotos.includes(index))removedPhotos.push(index);const t=editingId?trips.find(x=>x.id===editingId):null;renderPhotoPreview(t?.photos||[])}
function removePendingPhoto(index){pendingPhotos.splice(index,1);const t=editingId?trips.find(x=>x.id===editingId):null;renderPhotoPreview(t?.photos||[])}
async function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=e=>{const img=new Image();img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=e.target.result};r.onerror=reject;r.readAsDataURL(file)})}
document.getElementById('fPhotos').addEventListener('change',async e=>{for(const file of [...e.target.files].slice(0,8)){if(!file.type.startsWith('image/'))continue;try{pendingPhotos.push(await compressImage(file))}catch(err){}}const t=editingId?trips.find(x=>x.id===editingId):null;renderPhotoPreview(t?.photos||[]);e.target.value=''})
function saveEditor(){
  const title=document.getElementById('fTitle').value.trim()||'New journey',locations=currentLocations();
  if(!locations.length){toast('Tilføj mindst én by og ét land');return}
  const base=editingId?trips.find(x=>x.id===editingId):null;const kept=(base?.photos||[]).filter((_,i)=>!removedPhotos.includes(i));const photos=[...kept,...pendingPhotos];
  const t={id:editingId||'trip_'+Date.now(),title,locations,start:document.getElementById('fStart').value,end:document.getElementById('fEnd').value,story:document.getElementById('fStory').value.trim(),tags:base?.tags||['NEW'],image:photos[0]||base?.image||'assets/vegas.svg',photos,schemaVersion:SCHEMA_VERSION};
  if(editingId)trips=trips.map(x=>x.id===editingId?t:x);else trips.unshift(t);
  if(persist()){closeEditor();showView('trips');toast(editingId?'Journey updated':'Journey added')}
}
function deleteTrip(id){const t=trips.find(x=>x.id===id);if(!t)return;if(confirm(`Delete “${t.title}”?`)){trips=trips.filter(x=>x.id!==id);persist();toast('Journey deleted')}}
function deleteCurrent(){if(editingId)deleteTrip(editingId);closeEditor()}
function exportData(){const blob=new Blob([JSON.stringify({schemaVersion:SCHEMA_VERSION,trips},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='travel-pokedex-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function importData(input){const file=input.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const incoming=(data.trips||data).map(normalizeTrip);if(!Array.isArray(incoming))throw Error();trips=incoming;if(persist())toast('Backup imported')}catch(e){toast('Kunne ikke importere filen')}};r.readAsText(file);input.value=''}
function renderAll(){renderHome();renderTrips();renderCollection();renderMore();renderExplore()}
renderAll();
